name: martabakdjoeragan_app
description: Martabak Djoeragan Application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.3+4 # "+" represents the versionCode such as 1, 2, 3, etc.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: 1.0.0
  shared_preferences: ^0.5.1+2
  provider: 4.3.2+2
  http: ^0.12.2
  dio:
  fluttertoast:
  font_awesome_flutter:
  shimmer:
  fl_chart: ^0.6.0
  loading:
  path_provider: ^1.4.4
  network_to_file_image: ^2.3.6
  connectivity: ^2.0.1
  flutter_masked_text: ^0.8.0
  # month_picker_dialog: ^0.3.2
  collection: any
  esc_pos_bluetooth: ^0.2.8
  esc_pos_utils: ^0.3.6
  escposprinter:
    git:
        url: https://github.com/marcusfelix/esc-pos-printer-flutter.git
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/djoeragan.png
    - images/jisoocu.jpg
    - images/martabak1.jpg
    - images/martabak2.jpg
    - images/martabak3.jpg
    - images/martabak4.jpg
    - images/martabak5.jpg
    - images/empty.png
    - images/support.png
    - images/splashscreen.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
    # - family: Maison Neue Mono
    #   fonts:
    #     - asset: fonts/Maison Neue Mono/MaisonNeueMono-Regular.otf
    #     - asset: fonts/Maison Neue Mono/MaisonNeueMono-Italic.otf
    #       style: italic
    #     - asset: fonts/Maison Neue Mono/MaisonNeueMono-Bold.otf
    #       weight: 700
    #     - asset: fonts/Maison Neue Mono/MaisonNeueMono-BoldItalic.otf
    #       style: italic
    #       weight: 700
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/Maison Neue Mono/TrajanPro.ttf
    #     - asset: fonts/Maison Neue Mono/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Maison Neue Mono
      fonts:
        - asset: fonts/Maison Neue Mono/MaisonNeueMono-Regular.otf
        - asset: fonts/Maison Neue Mono/MaisonNeueMono-Italic.otf
          style: italic
        - asset: fonts/Maison Neue Mono/MaisonNeueMono-Bold.otf
          weight: 700
        - asset: fonts/Maison Neue Mono/MaisonNeueMono-BoldItalic.otf
          style: italic
          weight: 700
    - family: Maison Neue
      fonts:
        - asset : fonts/Maison Neue/MaisonNeue-Book.otf
        - asset : fonts/Maison Neue/MaisonNeue-Book.otf
          weight : 700
        - asset : fonts/Maison Neue/MaisonNeue-BookItalic.otf
          style : italic
    - family: PrintIcon
      fonts: 
        - asset: fonts/PrintIcon.ttf
        