/// Flutter icons CustomIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData th_large = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cw = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xf1f8, fontFamily: _kFontFam);
  static const IconData cart_plus = const IconData(0xf217, fontFamily: _kFontFam);
  static const IconData sticky_note_o = const IconData(0xf24a, fontFamily: _kFontFam);
  static const IconData credit_card_alt = const IconData(0xf283, fontFamily: _kFontFam);
}
