/// Flutter icons PrintIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrintIcon
///      fonts:
///       - asset: fonts/PrintIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PrintIcon {
  PrintIcon._();

  static const _kFontFam = 'PrintIcon';

  static const IconData print_setting = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe801, fontFamily: _kFontFam);
}
